PVP-K410/Calendar

app/src/main/java/com/pvp/app/common/Utils.kt
app/src/main/java/com/pvp/app/ui/screen/task/TaskScreen.kt

Dummy tasks for preview created at TaskScreen.

PVP 109 added task cards fore each type of task

---

.gitignore
app/build.gradle.kts
app/src/main/java/com/pvp/app/ui/screen/task/GeneralTaskCreationForm.kt
build.gradle.kts
gradle/wrapper/gradle-wrapper.properties

- Update project dependencies
- Update gradle-wrapper
- Alter code fragments for changed compose DatePickerState API
- Add single signing-config debug/release configurations
- Add configuration.properties to .gitignore
I went a little out of scope and renamed some of the variables in component that used `DatePickerState`.
I am also unsure if provided `**/configuration.properties` will hide that file from everywhere. In case it doesn't, please comment it.
Configuration file for single signingConfigs will be shared privately.

Project update

---

app/src/main/java/com/pvp/app/ui/router/Routes.kt
app/src/main/java/com/pvp/app/ui/screen/authentication/AuthenticationViewModel.kt
app/src/main/java/com/pvp/app/ui/screen/authentication/SignInScreen.kt
app/src/main/res/values/strings.xml

- Added primitive login process that is almost doing the same as register process
In the future validation and inputs form will be added to make these two (login & register) processes different from each other.

PVP-148 Add login process

---

app/build.gradle.kts
app/proguard-rules.pro
app/src/main/AndroidManifest.xml
app/src/main/res/values/strings.xml

Also separated application name into `Calendar` and `Calendar (Debug)`, depending on which build variant it is built.

hotfix // Adjust proguard rules to support serialization

---

app/src/main/java/com/pvp/app/api/AuthenticationService.kt
app/src/main/java/com/pvp/app/di/AuthenticationModule.kt
app/src/main/java/com/pvp/app/model/Authentication.kt
app/src/main/java/com/pvp/app/service/AuthenticationServiceImpl.kt
app/src/main/java/com/pvp/app/service/UserServiceImpl.kt
app/src/main/java/com/pvp/app/ui/screen/authentication/AuthenticationViewModel.kt
app/src/main/java/com/pvp/app/ui/screen/authentication/SignInScreen.kt
app/src/main/java/com/pvp/app/ui/screen/authentication/SignUpScreen.kt
app/src/main/res/values/strings.xml

- Added authentication validation
- Upon sign-in checks whether such email exists (if no - informs, breaks process)
- Upon sign-up checks whether such emails exists (if yes - informs, breaks process)
- Added standard google sign-in process in case the user has no google account set to use

PVP-149 Add authentication validation

---

app/src/main/java/com/pvp/app/Activity.kt
app/src/main/java/com/pvp/app/api/UserService.kt
app/src/main/java/com/pvp/app/service/AuthenticationServiceImpl.kt
app/src/main/java/com/pvp/app/service/UserServiceImpl.kt
app/src/main/java/com/pvp/app/ui/common/Components.kt
app/src/main/java/com/pvp/app/ui/screen/calendar/CalendarViewModel.kt
app/src/main/java/com/pvp/app/ui/screen/calendar/MonthlyCalendarViewModel.kt
app/src/main/java/com/pvp/app/ui/screen/layout/LayoutScreenAuthenticated.kt
app/src/main/java/com/pvp/app/ui/screen/layout/LayoutScreenUnauthenticated.kt
app/src/main/java/com/pvp/app/ui/screen/layout/LayoutViewModel.kt
app/src/main/java/com/pvp/app/ui/screen/profile/ProfileViewModel.kt
app/src/main/java/com/pvp/app/ui/screen/survey/SurveyViewModel.kt
app/src/main/java/com/pvp/app/ui/screen/task/TaskViewModel.kt

- UserService#getCurrent -> UserService#user
- AuthenticationService#user now uses callbackFlow and listen to FirebaseAuth changes
- ProgressIndicator supports new parameters: modifier for its box and color for itself
- Moved CalendarTheme and Surface to top level so that whole application has the theme at all times

REFACTOR // Surveys state handling and other misc things

---

app/src/main/java/com/pvp/app/ui/screen/drawer/DrawerScreen.kt
app/src/main/java/com/pvp/app/ui/screen/drawer/DrawerViewModel.kt
app/src/main/java/com/pvp/app/ui/screen/profile/ProfileScreen.kt
app/src/main/java/com/pvp/app/ui/screen/profile/ProfileViewModel.kt
app/src/main/java/com/pvp/app/ui/screen/survey/SurveyViewModel.kt

PVP-189 Transfer sign out action to navigation drawer

---

app/src/main/java/com/pvp/app/Application.kt
app/src/main/java/com/pvp/app/api/Configuration.kt
app/src/main/java/com/pvp/app/api/ExperienceService.kt
app/src/main/java/com/pvp/app/api/PointService.kt
app/src/main/java/com/pvp/app/common/Utils.kt
app/src/main/java/com/pvp/app/di/ServiceModule.kt
app/src/main/java/com/pvp/app/model/Points.kt
app/src/main/java/com/pvp/app/model/User.kt
app/src/main/java/com/pvp/app/service/ConfigurationImpl.kt
app/src/main/java/com/pvp/app/service/ExperienceServiceImpl.kt
app/src/main/java/com/pvp/app/service/PointServiceImpl.kt
app/src/main/java/com/pvp/app/service/TaskServiceImpl.kt
app/src/main/java/com/pvp/app/worker/TaskPointsDeductionWorker.kt
app/src/main/java/com/pvp/app/worker/TaskPointsDeductionWorkerSetup.kt

- Added points deduction for uncompleted tasks
- Added a coroutine worker that executes periodically (daily). It is created upon application's installation.
- Users are able to reclaim tasks that were not completed in last 2 days (to get points back)

PVP-174 PVP-176 Add points deduction for uncompleted tasks and leveling system

---

app/src/main/java/com/pvp/app/api/ExperienceService.kt
app/src/main/java/com/pvp/app/model/User.kt
app/src/main/java/com/pvp/app/service/ExperienceServiceImpl.kt
app/src/main/java/com/pvp/app/ui/common/Components.kt
app/src/main/java/com/pvp/app/ui/screen/calendar/CalendarWeeklyScreen.kt
app/src/main/java/com/pvp/app/ui/screen/filters/FiltersComponents.kt
app/src/main/java/com/pvp/app/ui/screen/profile/ProfileScreen.kt
app/src/main/java/com/pvp/app/ui/screen/profile/ProfileViewModel.kt
app/src/main/java/com/pvp/app/ui/screen/survey/Surveys.kt

- Changed how experience is calculated
- Cleaned up profile editing a little
- Added missing experience, points showcase to the profile and applied other things according to the design

CHORE Experience showcase within profile

---

app/build.gradle.kts
app/src/main/java/com/pvp/app/Activity.kt
build.gradle.kts

- Implemented notification permission handler:
- Detect whether notifications are disabled for the entire app or for individual notification channels.
- Display a dialog upon app launch if notifications are disabled, providing an option to navigate to settings.
- Updated Gradle to version 8.3.1.

PVP-167 Notification permission handler

---

app/build.gradle.kts
app/src/main/java/com/pvp/app/worker/DrinkReminderWorker.kt
build.gradle.kts

Recommended intake = 2.5L
Cup volume = 1L
Scheduled notifications: 1L, 1L, 0.5L

PVP-227 Fix hydration reminder calculation

---

app/src/main/java/com/pvp/app/ui/screen/profile/ProfileScreen.kt

The profile screen now contains a weekly activities box, where weekly activities are shown:

PVP-226: Add a screen showcasing weekly activities

---

app/src/main/java/com/pvp/app/ui/screen/friends/FriendsScreen.kt

- Added a badge onto friend requests button that is shown only when user has received >0 friend requests

PVP-244 Add a badge indicating user's received friend requests count

---

app/src/main/java/com/pvp/app/ui/screen/layout/LayoutScreenAuthenticated.kt
app/src/main/java/com/pvp/app/ui/screen/layout/RewardDialog.kt

Applied reward pop up design to RewardDialog and moved the composable to its own file.
Now it looks like this:

PVP-249 Applied reward popup design

---

app/src/main/java/com/pvp/app/ui/screen/authentication/AuthenticationScreen.kt
app/src/main/java/com/pvp/app/ui/screen/calendar/CalendarMonthlyScreen.kt
app/src/main/java/com/pvp/app/ui/screen/calendar/TasksOfDay.kt
app/src/main/java/com/pvp/app/ui/screen/goals/GoalCreation.kt
app/src/main/java/com/pvp/app/ui/screen/goals/GoalScreen.kt

Fixed some clickable box components so that the shape of the component and the click effect for that component match.

PVP-261 ensured click shape matches components shape

---

app/src/main/java/com/pvp/app/ui/screen/friends/FriendScreen.kt
app/src/main/java/com/pvp/app/ui/screen/friends/FriendsViewModel.kt
app/src/main/java/com/pvp/app/ui/screen/friends/Models.kt

Replaced previously dummy data (calories burned and steps made in the last 7 days) with real data we collect and upload to the database.

PVP-273 Replaced dummy data in friends screen

---

app/src/main/java/com/pvp/app/ui/common/Components.kt
app/src/main/java/com/pvp/app/ui/common/Locals.kt
app/src/main/java/com/pvp/app/ui/screen/authentication/AuthenticationScreen.kt
app/src/main/java/com/pvp/app/ui/screen/calendar/Analyses.kt
app/src/main/java/com/pvp/app/ui/screen/calendar/CalendarMonthlyScreen.kt
app/src/main/java/com/pvp/app/ui/screen/decoration/DecorationScreen.kt
app/src/main/java/com/pvp/app/ui/screen/drawer/DrawerScreen.kt
app/src/main/java/com/pvp/app/ui/screen/goals/GoalCreation.kt
app/src/main/java/com/pvp/app/ui/screen/layout/LayoutScreenBootstrap.kt
app/src/main/java/com/pvp/app/ui/screen/profile/ProfileScreen.kt
app/src/main/java/com/pvp/app/ui/screen/settings/SettingsScreen.kt
app/src/main/java/com/pvp/app/ui/screen/survey/SurveyScreen.kt

- Modified Composables that used toasts to be made of scaffolds that allow showing of snackbars
- Created CenteredSnackbarHost that centers the text which looks nicer
This is how they look now:

PVP 290 Changed toasts to snackbars

---

app/src/main/java/com/pvp/app/service/DecorationServiceImpl.kt

Also added comments highlighting which decoration is applied first and last.

PVP-281 Ensured accessory decorations are drawn last

---

app/src/main/java/com/pvp/app/api/ExerciseService.kt
app/src/main/java/com/pvp/app/service/ExerciseServiceImpl.kt
app/src/main/java/com/pvp/app/worker/WeeklyActivityWorker.kt

The most frequent activity that the user participates in is always added to the weekly activities generated.

PVP-283 Ensured weekly activities contain activities user participates in

---

app/src/main/java/com/pvp/app/api/FeedbackService.kt
app/src/main/java/com/pvp/app/di/ServiceModule.kt
app/src/main/java/com/pvp/app/model/Feedback.kt
app/src/main/java/com/pvp/app/service/FeedbackServiceImpl.kt
app/src/main/java/com/pvp/app/ui/screen/drawer/DrawerScreen.kt
app/src/main/java/com/pvp/app/ui/screen/feedback/FeedbackForm.kt
app/src/main/java/com/pvp/app/ui/screen/feedback/FeedbackViewModel.kt
app/src/main/res/values-lt/strings.xml
app/src/main/res/values/strings.xml

- Created Feedback model and implemented FeedbackService to upload feedback entries to the database
- Created feedback form and feedback dialog that contains the form
- Users can choose to report bug or request a feature, fill description and rate the app from 0 stars to 5 stars
- Feedback dialog can be opened from the drawer upon pressing clickable text on the bottom left of the sign out button
This is how it looks like:

PVP 289 Added feedback form
